package me.comandos;

import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import me.main.Main;

public class ClearChat implements CommandExecutor {

	@Override
	public boolean onCommand(CommandSender sender, Command cmd, String arg2, String[] arg3) {
		if(!(sender instanceof Player)) {
			sender.sendMessage("§c§lVoce Não é um Player!");
			return true;
		}
		for (Player s : Bukkit.getOnlinePlayers()) {
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage("");
			s.sendMessage(" ");
			s.sendMessage(" ");
			s.sendMessage(" ");
			s.sendMessage(" ");
			s.sendMessage(" ");
			s.sendMessage(" ");
			s.sendMessage(" ");
			s.sendMessage(Main.tag + " §a§lO Chat foi Limpo");
		}
		return false;
	}

}